---
title: '732A73: Bayesian Learning'
author: "Oriol Garrobé, Dávid Hrabovszki"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  pdf_document: default
  html_document: default
subtitle: Computer Lab 2
header-includes: \usepackage{float}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, eval=TRUE)
```

```{r warning = FALSE, include=FALSE}
# R version
RNGversion('3.5.1')

# libraries
library("mvtnorm")
```

# Question 1. Linear and polynomial regression.

Given the dataset \texttt{TempLinkoping.txt} containing:
* Temp: Response variable with daily average of temperatures in Linkoping over 2018.
* Time: Covariate of Temp computed as

$$
time=\frac{number\ of\ days\ since\ beginning\ of\ the\ year}{365}
$$

We are asked to perform Bayesian analysis of a quadratic regression

$$
temp=\beta_0 + \beta_1 \cdot time + \beta_2 \cdot time^2 + \epsilon, \epsilon \sim N(0,\sigma^2).
$$


### (a)
```{r}
############################################################
###### Question 1. Linear and polynomial regression  #######
############################################################

### (a)

data <- read.table("TempLinkoping.txt", header = TRUE)

y <- data$temp
time <- data$time

n <- length(y)
X <- cbind(matrix(1, nrow = length(y)),time,time^2)

# Initial prior hyperparameters
mu_0 <- c(-10,100,-100)
omega_0 <- 0.1*diag(3)
nu_0 <- 4
sigma2_0 <- 1

# Conjugate prior
compute_betas <- function(N_draws, mu_0, omega_0, nu_0, sigma2_0){
  draw_sigma2 <- nu_0*sigma2_0/rchisq(Ndraws, nu_0)
  draw_beta <- matrix(0, nrow=length(draw_sigma2), ncol=3 )
  for (sigma in draw_sigma2) {
    i <- which(draw_sigma2==sigma)
    draw_beta[i,] <- rmvnorm(1, mu_0, sigma*omega_0)
  }
  return(colMeans(draw_beta))
}

Ndraws=1000

# Tune hyperparameters

# Initial hyperparameters
beta_0 <- compute_betas(Ndraws, mu_0, omega_0, nu_0, sigma2_0)

# 1st iteration
mu_1 <- c(-5,90,-90)
beta_1 <- compute_betas(Ndraws, mu_1, omega_0, nu_0, sigma2_0)

# 2nd iteration
mu_2 <- c(0,100,-100)
beta_2 <- compute_betas(Ndraws, mu_2, omega_0, nu_0, sigma2_0)

# 3rd iteration
mu_3 <- c(0,85,-85)
beta_3 <- compute_betas(Ndraws, mu_3, omega_0, nu_0, sigma2_0)

# 4th iteration
mu_4 <- c(-5, 85, -85)
beta_4 <- compute_betas(Ndraws, mu_4, omega_0, nu_2, sigma2_0)
```

```{r}
plot(time, X %*% beta_0, type = 'l', lwd=2, col='red', ylim=c(-10, 25),
     ylab='Temperature', xlab='Time')
points(time, X %*% beta_1, lwd=2, col='blue', type='l')
points(time, X %*% beta_2, lwd=2, col='pink', type='l')
points(time, X %*% beta_3, lwd=2, col='green', type='l')
points(time, X %*% beta_4, lwd=2, col='yellow', type='l')
```

### (b)

```{r}



```




